services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    environment:
      DB_HOSTNAME: immich_postgres
      DB_PASSWORD: ${IMMICH_DB_PASSWORD}
      DB_USERNAME: postgres
      DB_DATABASE_NAME: immich
      # IMMICH_LOG_LEVEL: verbose
      postgres: postgres
      immich: immich
      REDIS_HOSTNAME: immich_redis
    volumes:
      - ${IMMICH_UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      # - ${CONFIG_ROOT:-.}/immich/healthcheck:/healthcheck
    depends_on:
      - immich-redis
      - immich-database
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.immich.rule=(Host(`${IMMICH_HOSTNAME}`))
      - traefik.http.routers.immich.tls=true
      - traefik.http.routers.immich.tls.certresolver=myresolver
      - traefik.http.services.immich.loadbalancer.server.port=2283
      - traefik.docker.network=docker-compose-nas
      - homepage.group=Apps
      - homepage.name=Immich
      - homepage.icon=immich.png
      - homepage.href=https://${IMMICH_HOSTNAME}
      - homepage.description=Self-hosted photo and video management solution
      - homepage.weight=4
      - homepage.widget.type=immich
      - homepage.widget.url=http://immich-server:2283
      - homepage.widget.key=${IMMICH_API_KEY}
      - homepage.widget.version=2
    profiles:
      - immich

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - immich-model-cache:/cache
    restart: always
    profiles:
      - immich

  immich-redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - immich

  immich-database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      DB_HOSTNAME: immich_postgres
      POSTGRES_PASSWORD: ${IMMICH_DB_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
      DB_STORAGE_TYPE: 'HDD'
    volumes:
      - ${CONFIG_ROOT:-.}/immich/postgresql:/var/lib/postgresql/data
    restart: always
    profiles:
      - immich

volumes:
  immich-model-cache:

networks:
  default:
    name: docker-compose-nas
    external: true
